# Generated by Django 6.0.4 on 2026-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_chatsession_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='session_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
