# Generated by Django 6.0.4 on 2026-05-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, choices=[('under15', 'أصغر من 15'), ('15plus', 'أكبر من 15')], max_length=20)),
                ('learning_style', models.CharField(blank=True, max_length=50)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('answer', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning_test.learningtestsession')),
            ],
            options={
                'ordering': ['question_order'],
                'unique_together': {('session', 'question_order')},
            },
        ),
    ]
